### ISSUE TITLE
HTML highlight is not as the Screenshot.

### ISSUE THREAD

**Issue by ctf0** [JeremySaks/wanderlei-color-scheme#1]
whats the name of the html syntax you are using ?
cuz atm anything within the `double quotes` is having the same colors ,and clearly the code in the screen shot is more of a template language (handlebars, mustache, etc..).

so can you give me the link to the template lang you are using in that SS ???

**Comment by JeremySaks** [comment]
Hi @ctf0 - the syntax highlighting in the screenshot is `handlebars` - I can clarify that in the readme. The syntax highlighting with `html` for me produces the correct output also (except for handlebars/mustache specific syntax of course). Let me know if that helps.

**Comment by ctf0** [comment]
sorry for the long delay, thanx for the info it did help with what i was after :+1:
